version: '4'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_ROOT_USERNAME: root
      MONGO_INIT_ROOT_PASSWORD: password
      MONGO_INIT_ROOT_DATABASE: product_service
    volumes:
      - ./data:/data/db